### PR TITLE
Navigation structure and sectionalization

### PR DESCRIPTION
**Pull request by dansysanalyst**
- Matches the top navigation structure found in other plugins page
- Divided into sections to provide an easier access on possible questions

### CODE REVIEW

**Review by owenvoke — APPROVED** [review]
Brilliant!

**Comment by owenvoke** [comment]
I've resolved the merge conflicts for you. 👍🏻

**Comment by octoper** [comment]
Can we merge it now @owenvoke ?

**Comment by owenvoke** [comment]
Merged! I had meant to, but got distracted by colleagues wishing me happy birthday. 😋

**Pull request merged**
