### PR TITLE
docs: update deprecated `<coverage>` config usage

### LINKED ISSUE #240: Code Coverage Section Incorrect for PHPUnit 10
Hey Nuno,

While setting up coverage with PHPUnit 10 this:

```xml
<coverage>
    <include>
        <directory suffix=".php">./app</directory>
    </include>
</coverage>
```

Is no longer valid.

This will throw the following:

> WARN  Test results may not be as expected because the XML configuration file did not pass validation:
>
> Line 20:
>  - Element 'include': This element is not expected.

Reading the v10 docs I'm at a loss to see how you specify include and exclude paths and files or I would have sent a PR for this.

### PR DESCRIPTION
**Pull request by owenvoke**
Closes #240

### CODE REVIEW

**Comment by secondmanveran** [comment]
@owenvoke 

How does this resolve the `coverage` issue? This page is about coverage, not source.

**Comment by owenvoke** [comment]
`<source>` is the replacement for determining which files to cover. Coverage now uses the include / exclude directories from `<source>`, rather than `<coverage>`.

**Comment by secondmanveran** [comment]
Gotcha.

There is still a `coverage` tag with props passed in that you may want to reference or maybe include a link to the docs.

And you're saying the I can still run a coverage report with no `coverage` tag in the xml file, and just move my includes and excludes to my `source` tag?

**Comment by owenvoke** [comment]
Yes, coverage will still work without the `<coverage>` tag, that's just for configuring additional things [like path coverage and report paths](https://docs.phpunit.de/en/10.4/configuration.html#the-coverage-element).

[asciicast](https://asciinema.org/a/lqroCbkL7j9ik03tuFCZKOBbj)

**Pull request merged**
