### PR TITLE
Adds documentation for higher order expectations

### PR DESCRIPTION
**Pull request by nedwors**
This PR adds documentation for Higher Order Expectations as introduced in [this PR](https://github.com/pestphp/pest-plugin-expectations/pull/12).

### CODE REVIEW

**Comment by lukeraymonddowning** [comment]
Beautiful. Worth showing an example with arrays too?

**Comment by nedwors** [comment]
> Beautiful. Worth showing an example with arrays too?

@lukeraymonddowning, good shout. Updated

**Comment by nunomaduro** [comment]
Announcing this tomorrow. @nedwors Do you have a blog to write an article about this?

**Comment by lukeraymonddowning** [comment]
@nunomaduro will share the URL when @nedwors has finished 👍

**Pull request merged**
