### PR TITLE
Update PHPUnit assertion API link

### PR DESCRIPTION
**Pull request by phildawson-gravity**
Current has a broken link and 11.0 now released

### CODE REVIEW

**Review by owenvoke — COMMENTED** [review]
The current link seems to work fine for me, and is correct as Pest 2.x uses PHPUnit 10.5 🤔

It looks like the issue is that the docs haven't updated on the `pestphp.com` site. I'm not sure how / when we update this, so @nunomaduro do you happen to know?

**Comment by phildawson-gravity** [comment]
> The current link seems to work fine for me

The current as in the live site, it's showing 10.0 rather than 10.5 as that hasn't been pulled.

Screenshot 2024-03-20 at 18 05 26

**Comment by nunomaduro** [comment]
Pest 2 uses PHPUnit 10

**Comment by phildawson-gravity** [comment]
> Pest 2 uses PHPUnit 10

The issue is the doc links to 10.0 which is broken and it should point to 10.5

https://docs.phpunit.de/en/10.5/assertions.html

**Comment by nunomaduro** [comment]
Cool, you can update all links to 10.5

**Comment by phildawson-gravity** [comment]
Looks to already be in the master from @Lubje last month so just needs the site updated as @owenvoke mentioned above.

https://github.com/pestphp/docs/commits/master/writing-tests.md

**Pull request closed without merging**
